# Generated by Django 4.0.1 on 2022-01-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('poster_link', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('register_deadline', models.DateTimeField()),
                ('host_email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(default='', max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('participant_email', models.EmailField(max_length=254)),
                ('registration_type', models.CharField(choices=[('GRP', 'GROUP'), ('SING', 'INDIVIDUAL')], max_length=20)),
                ('no_of_people', models.IntegerField(default=1)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em_app.event')),
            ],
        ),
    ]
