# Generated by Django 3.2.11 on 2022-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_app', '0003_rename_no_of_people_participant_num_of_ppl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registration_type',
            field=models.CharField(max_length=50),
        ),
    ]
